FROM --platform=$BUILDPLATFORM quay.io/konveyor/builder:ubi9-latest AS builder
ARG BUILDPLATFORM
ARG TARGETOS
ARG TARGETARCH

ENV GOPATH=$APP_ROOT

COPY . $APP_ROOT/src/velero-plugin-for-microsoft-azure

WORKDIR $APP_ROOT/src/velero-plugin-for-microsoft-azure

RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -v -o $APP_ROOT/bin/velero-plugin-for-microsoft-azure -mod=mod ./velero-plugin-for-microsoft-azure

FROM registry.access.redhat.com/ubi9-minimal
RUN mkdir /plugins
COPY --from=builder /opt/app-root/bin/velero-plugin-for-microsoft-azure /plugins/
USER 65534:65534
ENTRYPOINT ["/bin/bash", "-c", "cp /plugins/* /target/."]
